/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, DataSource as PrismaDataSource } from "@prisma/client";

export class DataSourceServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.DataSourceCountArgs, "select">
  ): Promise<number> {
    return this.prisma.dataSource.count(args);
  }

  async dataSources(
    args: Prisma.DataSourceFindManyArgs
  ): Promise<PrismaDataSource[]> {
    return this.prisma.dataSource.findMany(args);
  }
  async dataSource(
    args: Prisma.DataSourceFindUniqueArgs
  ): Promise<PrismaDataSource | null> {
    return this.prisma.dataSource.findUnique(args);
  }
  async createDataSource(
    args: Prisma.DataSourceCreateArgs
  ): Promise<PrismaDataSource> {
    return this.prisma.dataSource.create(args);
  }
  async updateDataSource(
    args: Prisma.DataSourceUpdateArgs
  ): Promise<PrismaDataSource> {
    return this.prisma.dataSource.update(args);
  }
  async deleteDataSource(
    args: Prisma.DataSourceDeleteArgs
  ): Promise<PrismaDataSource> {
    return this.prisma.dataSource.delete(args);
  }
}
